" vim:ts=4:sw=4:noet:
" =================================================================
" notepad.vim - my fancy color file
" Original author - Thomas Schumm <phong@phong.org>
"
" This file is generated by a script.
" Last generated: 2003-11-22: Thomas Schumm <phong@phong.org>
" =================================================================
let g:colors_name="notepad"

if &term == "cygwin" || &term == "putty" || &term == "rxvt" " {{{
	" This lets you use bright backgrounds on some terminals that
	" otherwise don't allow it.  Doesn't work with the 'reverse'
	" attribute, but could be made to do so (but is a waste of time
	" because reverse is sorta redundant if you can explicitly
	" specify a foreground and background)
	set t_Co=16
	set t_AF=[3%{7}%p1%&%d%{7}%p1%<%Pa%?%ga%t;1%;m
	set t_AB=[4%{7}%p1%&%d%{7}%p1%<%Pa%?%ga%t;5%;m
endif " }}}

" ----------------------------------------------------------------------
" We have a color term or gui
" ----------------------------------------------------------------------
if &t_Co >= 8 || has("gui_running")
	set background=dark
	if version >= 600
	hi clear
		syntax enable
	else
		syntax on
	endif
	set nohlsearch
	" We have GUI {{{
	if has("gui_running")
		if ($USER) == "root"
			hi StatusLine guifg=#000000 guibg=#ff5555 gui=NONE
			hi User1 guifg=#aa0000 guibg=#ff5555 gui=NONE
		else
			hi StatusLine guifg=#000000 guibg=#0000aa gui=NONE
			hi User1 guifg=#aa0000 guibg=#0000aa gui=NONE
		endif
		hi Normal guifg=#555555 guibg=#ffffff gui=NONE
		hi StatusLineNC guifg=#555555 guibg=#aaaaaa gui=NONE
		hi SpecialKey guifg=#00aa00 guibg=#5555ff gui=NONE
		hi VisibleWS guifg=#aaaaaa gui=NONE
		hi IncSearch guifg=#ffffff guibg=#000000 gui=NONE
		hi Search guifg=#ffffff guibg=#aa5500 gui=NONE
		hi WildMenu guifg=#ffffff guibg=#aa5500 gui=NONE
		hi Folded guifg=#000000 guibg=#aaaaaa gui=NONE
		hi FoldColumn guifg=#00aa00 guibg=#aaaaaa gui=NONE
		hi VertSplit guifg=#555555 guibg=#aaaaaa gui=NONE
		hi Error guifg=#000000 guibg=#aa0000 gui=NONE
		hi Todo guifg=#55ffff guibg=#aa5500 gui=NONE
		hi NonText guifg=#00aa00 gui=NONE
		hi Directory guifg=#00aaaa gui=NONE
		hi ErrorMsg guifg=#000000 guibg=#ff5555 gui=NONE
		hi MoreMsg guifg=#00aa00 gui=NONE
		hi ModeMsg guifg=#aa5500 guibg=#ff5555 gui=NONE
		hi LineNr guifg=#ff5555 gui=NONE
		hi Question guifg=#00aa00 gui=NONE
		hi Visual guifg=#ffffff guibg=#55ffff gui=NONE
		hi VisualNOS guifg=#ffffff guibg=#55ff55 gui=NONE
		hi Title guifg=#aa00aa gui=NONE
		hi WarningMsg guifg=#000000 guibg=#ffff55 gui=NONE
		hi DiffAdd guifg=#aa5500 guibg=#55ff55 gui=NONE
		hi DiffDelete guifg=#aaaaaa guibg=#5555ff gui=NONE
		hi DiffChange guifg=#000000 guibg=#5555ff gui=NONE
		hi DiffText guifg=#000000 guibg=#55ff55 gui=NONE
		hi Comment guifg=#0000aa gui=NONE
		hi Constant guifg=#00aa00 gui=NONE
		hi Special guifg=#00aaaa gui=NONE
		hi Delimiter guifg=#55ffff gui=NONE
		hi Operator guifg=#55ffff gui=NONE
		hi Identifier guifg=#aa5500 gui=NONE
		hi Statement guifg=#000000 gui=NONE
		hi PreProc guifg=#55ff55 gui=NONE
		hi Exception guifg=#55ff55 gui=NONE
		hi Type guifg=#00aaaa gui=NONE
		hi StorageClass guifg=#aa5500 gui=NONE
		hi Underlined guifg=#0000aa gui=NONE,underline
		hi Ignore guifg=#aaaaaa gui=NONE
		hi cssBraces guifg=#55ffff gui=NONE
		hi mySpecialChars guifg=#55ffff gui=NONE
		hi perlConditionalOperator guifg=#55ffff gui=NONE
		hi phpSemiComma guifg=#55ffff gui=NONE
		hi htmlItalic guifg=#00aaaa gui=NONE
		hi htmlBold guifg=#aa0000 gui=NONE
		hi htmlSpecialChar guifg=#000000 gui=NONE
	" }}}

	" Terminal, bright backgrounds are available {{{
	elseif &t_Co >= 16
		if ($USER) == "root"
			hi StatusLine ctermfg=Black ctermbg=LightRed cterm=NONE
			hi User1 ctermfg=DarkRed ctermbg=LightRed cterm=NONE
		else
			hi StatusLine ctermfg=Black ctermbg=DarkBlue cterm=NONE
			hi User1 ctermfg=DarkRed ctermbg=DarkBlue cterm=NONE
		endif
		hi Normal ctermfg=DarkGray ctermbg=White cterm=NONE
		hi StatusLineNC ctermfg=DarkGray ctermbg=Gray cterm=NONE
		hi SpecialKey ctermfg=DarkGreen ctermbg=LightBlue cterm=NONE
		hi VisibleWS ctermfg=Gray cterm=NONE
		hi IncSearch ctermfg=White ctermbg=Black cterm=NONE
		hi Search ctermfg=White ctermbg=Brown cterm=NONE
		hi WildMenu ctermfg=White ctermbg=Brown cterm=NONE
		hi Folded ctermfg=Black ctermbg=Gray cterm=NONE
		hi FoldColumn ctermfg=DarkGreen ctermbg=Gray cterm=NONE
		hi VertSplit ctermfg=DarkGray ctermbg=Gray cterm=NONE
		hi Error ctermfg=Black ctermbg=DarkRed cterm=NONE
		hi Todo ctermfg=LightCyan ctermbg=Brown cterm=NONE
		hi NonText ctermfg=DarkGreen cterm=NONE
		hi Directory ctermfg=DarkCyan cterm=NONE
		hi ErrorMsg ctermfg=Black ctermbg=LightRed cterm=NONE
		hi MoreMsg ctermfg=DarkGreen cterm=NONE
		hi ModeMsg ctermfg=Brown ctermbg=LightRed cterm=NONE
		hi LineNr ctermfg=LightRed cterm=NONE
		hi Question ctermfg=DarkGreen cterm=NONE
		hi Visual ctermfg=White ctermbg=LightCyan cterm=NONE
		hi VisualNOS ctermfg=White ctermbg=LightGreen cterm=NONE
		hi Title ctermfg=DarkMagenta cterm=NONE
		hi WarningMsg ctermfg=Black ctermbg=Yellow cterm=NONE
		hi DiffAdd ctermfg=Brown ctermbg=LightGreen cterm=NONE
		hi DiffDelete ctermfg=Gray ctermbg=LightBlue cterm=NONE
		hi DiffChange ctermfg=Black ctermbg=LightBlue cterm=NONE
		hi DiffText ctermfg=Black ctermbg=LightGreen cterm=NONE
		hi Comment ctermfg=DarkBlue cterm=NONE
		hi Constant ctermfg=DarkGreen cterm=NONE
		hi Special ctermfg=DarkCyan cterm=NONE
		hi Delimiter ctermfg=LightCyan cterm=NONE
		hi Operator ctermfg=LightCyan cterm=NONE
		hi Identifier ctermfg=Brown cterm=NONE
		hi Statement ctermfg=Black cterm=NONE
		hi PreProc ctermfg=LightGreen cterm=NONE
		hi Exception ctermfg=LightGreen cterm=NONE
		hi Type ctermfg=DarkCyan cterm=NONE
		hi StorageClass ctermfg=Brown cterm=NONE
		hi Underlined ctermfg=DarkBlue cterm=NONE,underline
		hi Ignore ctermfg=Gray cterm=NONE
		hi cssBraces ctermfg=LightCyan cterm=NONE
		hi mySpecialChars ctermfg=LightCyan cterm=NONE
		hi perlConditionalOperator ctermfg=LightCyan cterm=NONE
		hi phpSemiComma ctermfg=LightCyan cterm=NONE
		hi htmlItalic ctermfg=DarkCyan cterm=NONE
		hi htmlBold ctermfg=DarkRed cterm=NONE
		hi htmlSpecialChar ctermfg=Black cterm=NONE
	" }}}

	" Bright backgrounds are not available {{{
	" Backgrounds must be specified as 'bold'
	else
		if ($USER) == "root"
			hi StatusLine ctermfg=Black ctermbg=LightRed cterm=NONE
			hi User1 ctermfg=DarkRed ctermbg=LightRed cterm=NONE
		else
			hi StatusLine ctermfg=Black ctermbg=DarkBlue cterm=NONE
			hi User1 ctermfg=DarkRed ctermbg=DarkBlue cterm=NONE
		endif
		hi Normal ctermfg=DarkGray ctermbg=White cterm=NONE,bold
		hi StatusLineNC ctermfg=Gray ctermbg=DarkGray cterm=NONE
		hi SpecialKey ctermfg=DarkGreen ctermbg=LightBlue cterm=NONE
		hi VisibleWS ctermfg=Gray cterm=NONE
		hi IncSearch ctermfg=White ctermbg=Black cterm=NONE,bold
		hi Search ctermfg=White ctermbg=Brown cterm=NONE,bold
		hi WildMenu ctermfg=White ctermbg=Brown cterm=NONE,bold
		hi Folded ctermfg=Brown ctermbg=DarkGray cterm=NONE
		hi FoldColumn ctermfg=DarkGreen ctermbg=DarkGray cterm=NONE
		hi VertSplit ctermfg=Gray ctermbg=DarkGray cterm=NONE
		hi Error ctermfg=Black ctermbg=DarkRed cterm=NONE
		hi Todo ctermfg=DarkCyan ctermbg=DarkGray cterm=NONE
		hi NonText ctermfg=DarkGreen cterm=NONE
		hi Directory ctermfg=DarkCyan cterm=NONE
		hi ErrorMsg ctermfg=Black ctermbg=LightRed cterm=NONE
		hi MoreMsg ctermfg=DarkGreen cterm=NONE
		hi ModeMsg ctermfg=Brown ctermbg=LightRed cterm=NONE
		hi LineNr ctermfg=LightRed cterm=NONE,bold
		hi Question ctermfg=DarkGreen cterm=NONE
		hi Visual ctermfg=White ctermbg=LightCyan cterm=NONE,bold
		hi VisualNOS ctermfg=White ctermbg=LightGreen cterm=NONE,bold
		hi Title ctermfg=DarkMagenta cterm=NONE
		hi WarningMsg ctermfg=Black ctermbg=Yellow cterm=NONE
		hi DiffAdd ctermfg=Brown ctermbg=LightGreen cterm=NONE
		hi DiffDelete ctermfg=Gray ctermbg=LightBlue cterm=NONE
		hi DiffChange ctermfg=Black ctermbg=LightBlue cterm=NONE
		hi DiffText ctermfg=Black ctermbg=LightGreen cterm=NONE
		hi Comment ctermfg=DarkBlue cterm=NONE
		hi Constant ctermfg=DarkGreen cterm=NONE
		hi Special ctermfg=DarkCyan cterm=NONE
		hi Delimiter ctermfg=LightCyan cterm=NONE,bold
		hi Operator ctermfg=LightCyan cterm=NONE,bold
		hi Identifier ctermfg=Brown cterm=NONE
		hi Statement ctermfg=Black cterm=NONE
		hi PreProc ctermfg=LightGreen cterm=NONE,bold
		hi Exception ctermfg=LightGreen cterm=NONE,bold
		hi Type ctermfg=DarkCyan cterm=NONE
		hi StorageClass ctermfg=Brown cterm=NONE
		hi Underlined ctermfg=DarkBlue cterm=NONE,underline
		hi Ignore ctermfg=Gray cterm=NONE
		hi cssBraces ctermfg=LightCyan cterm=NONE,bold
		hi mySpecialChars ctermfg=LightCyan cterm=NONE,bold
		hi perlConditionalOperator ctermfg=LightCyan cterm=NONE,bold
		hi phpSemiComma ctermfg=LightCyan cterm=NONE,bold
		hi htmlItalic ctermfg=DarkCyan cterm=NONE
		hi htmlBold ctermfg=DarkRed cterm=NONE
		hi htmlSpecialChar ctermfg=Black cterm=NONE
	endif " }}}

endif
